services:
  - type: web
    name: selenium-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "python auth.py"
    envVars:
      - key: CHROME_BIN
        value: "chromium-browser"
      - key: CHROMEDRIVER_PATH
        value: "/chromedriver"
