services:
  - type: worker
    name: twitter-automation-worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python auth.py
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
